# Generated by Django 5.0 on 2023-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
