# Generated by Django 5.0 on 2023-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0003_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcomplex',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drillcomplex',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
