# Generated by Django 5.0 on 2023-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0004_drillcomplex_is_active_drillcomplex_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillcomplex',
            name='drills',
            field=models.ManyToManyField(null=True, related_name='complexes', to='drills.drill'),
        ),
        migrations.AlterField(
            model_name='drillcomplex',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
