# Generated by Django 5.0 on 2024-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0005_alter_drillcomplex_drills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
